name: On PR Changed, Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronized, closed ]

jobs:
  build-test:
    strategy:
      matrix:
        python-version: ["3.x"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Run PyLint Check
      run: |
        pylint --fail-under=10.0 totolo

    - name: Test with PyTest
      run: |
        pytest --cov-report=xml --cov-fail-under=100 --cov=totolo tests/
